import Head from "next/head";

import { Footer, Navbar } from "../components/Common";
import {Banner, Section} from "../components/Home"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Banner/>
        <Section/>
        <Footer />
      </main>
    </div>
  );
}
